export const environment = {
  loginUrl: 'http://localhost:8080/login',
  signupUrl: 'http://localhost:8080/signup',
  getUserUrl: 'http://localhost:8080/user/user',
  updateUserUrl: 'http://localhost:8080/user/update',
  getUsersUrl: 'http://localhost:8080/user/all-users',
  createUserUrl: 'http://localhost:8080/user/create-user',
  createArticleUrl: 'http://localhost:8080/article/add-Article',
  createNewsUrl: 'http://localhost:8080/news/add-news',
  createShortReadsUrl: 'http://localhost:8080/short-reads/add-ShortReads',
  getUserNewsUrl: 'http://localhost:8080/usernews/getUserNewsPending',
  userNewsAcceptUrl: 'http://localhost:8080/usernews/acceptUserNews',
  userNewsRejectUrl: 'http://localhost:8080/usernews/rejectUserNews',
  getRejectedNewsUrl: 'http://localhost:8080/news/get-rejected-News',
  getRejectedArticleUrl: 'http://localhost:8080/article/get-rejected-article',
  getRejectedShortReadsUrl:
    'http://localhost:8080/short-reads/get-Rejected-ShortReads',
  getPendingNewsUrl: 'http://localhost:8080/news/get-pending-News',
  newsAcceptUrl: "http://localhost:8080/news/acceptNews",
  newsRejectUrl: "http://localhost:8080/news/rejectNews",
  getPendingArticleUrl: "http://localhost:8080/article/get-pending-article",
  articleAcceptUrl: "http://localhost:8080/article/acceptArticle",
  articleRejectUrl: "http://localhost:8080/article/rejectArticle",
  getPendingShortReadsUrl: "http://localhost:8080/short-reads/get-Pending-ShortReads",
  shortReadsAcceptUrl: "http://localhost:8080/short-reads/acceptShortReads",
  shortReadsRejectUrl: "http://localhost:8080/short-reads/rejectShortReads",
  getUserNewsAcceptedUrl: "http://localhost:8080/usernews/getUserNews",
  searchUrl: "http://localhost:8080/news/search-news",
  getShortReadsUrl: "http://localhost:8080/short-reads/get-all-ShortReads",
  getShortReadsByIdUrl: "http://localhost:8080/short-reads/get-ShortReads",
  getArticleUrl: "http://localhost:8080/article/get-all-article",
  getArticle: "http://localhost:8080/article/get-article",
  increaseArticleViews: "http://localhost:8080/article/increaseViews",
  increaseShortReadsViews: "http://localhost:8080/short-reads/increaseViews",
  dailyNewsUrl: "http://localhost:8080/news/get-today-news",
  userNewsUrl: 'http://localhost:8080/usernews/addMyNews',
  getNewsByIdUrl: "http://localhost:8080/news/get-News",
  increaseNewsUrl: "http://localhost:8080/news/increaseViews",
  getBreakingNewsUrl: "http://localhost:8080/news/get-breaking-news",
  getCategoryNewsUrl: "http://localhost:8080/news/category-news",
  getSensationalNewsUrl: "http://localhost:8080/news/get-sensational-news",
};
